"use client";

import { Check, FileSpreadsheet, LoaderCircle, UploadCloud, X, AlertTriangle } from "lucide-react";
import { DragEvent, useRef, useState } from "react";
import { ImportPreview } from "@/lib/types";

export function ImportFlow() {
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File>(); const [preview, setPreview] = useState<ImportPreview>(); const [loading, setLoading] = useState(false); const [result, setResult] = useState<string>(); const [error, setError] = useState<string>();
  function choose(next?: File) { if (!next) return; setFile(next); setPreview(undefined); setResult(undefined); setError(undefined); }
  async function post(path: string) { if (!file) return; setLoading(true); setError(undefined); const data = new FormData(); data.append("file", file); try { const response = await fetch(path, { method: "POST", body: data }); if (!response.ok) throw new Error(await response.text()); const body = await response.json(); if (path.endsWith("preview")) setPreview(body); else { setResult(`${body.importedCount} trips imported${body.skippedCount ? `, ${body.skippedCount} skipped` : ""}.`); setPreview(undefined); } } catch (e) { setError(e instanceof Error ? e.message : "Import failed."); } finally { setLoading(false); } }
  function drop(e: DragEvent) { e.preventDefault(); choose(e.dataTransfer.files[0]); }
  return <div className="import-flow"><div className="import-steps"><span className="current">1 <small>Choose file</small></span><i /><span className={preview ? "current" : ""}>2 <small>Review</small></span><i /><span className={result ? "current" : ""}>3 <small>Import</small></span></div>
    {!preview && !result && <section className="dropzone" onDragOver={e => e.preventDefault()} onDrop={drop}><input hidden ref={input} type="file" accept=".xlsx,.csv" onChange={e => choose(e.target.files?.[0])} />{file ? <><FileSpreadsheet /><h2>{file.name}</h2><p>{(file.size / 1024).toFixed(1)} KB · Ready to preview</p><button className="text-button" onClick={() => setFile(undefined)}>Choose a different file</button></> : <><UploadCloud /><h2>Drop your trip log here</h2><p>Upload the historical spreadsheet or a CSV export.</p><button className="button" onClick={() => input.current?.click()}>Browse files</button><small>.XLSX or .CSV</small></>} {file && <button className="button" disabled={loading} onClick={() => post("/api/imports/trips/preview")}>{loading ? <LoaderCircle className="spin" /> : null} Preview trips</button>}</section>}
    {preview && <section className="preview"><div className="preview-summary"><div><span>Rows read</span><strong>{preview.rowsRead}</strong></div><div className="good"><span>Ready</span><strong>{preview.importableRows}</strong></div><div className="warn"><span>Skipped</span><strong>{preview.skippedRows}</strong></div></div><div className="preview-table"><div className="preview-row head"><span>Status</span><span>Source</span><span>Waterway</span><span>Date</span><span>Miles</span></div>{preview.rows.slice(0, 50).map(row => <div className="preview-row" key={row.sourceRow}><span>{row.canImport ? <Check className="ok" /> : <X className="bad" />}</span><span>Row {row.sourceRow}</span><strong>{row.riverName || "Missing river"} {row.state && <small>{row.state}</small>}</strong><span>{row.startDate || row.sourceDateText || "Unknown"}</span><span>{row.distanceMiles ?? "—"}{row.warnings?.length ? <i title={row.warnings.join("\n")}><AlertTriangle /></i> : null}</span></div>)}</div>{preview.rows.length > 50 && <p className="muted">Showing the first 50 of {preview.rows.length} rows.</p>}<div className="preview-actions"><button className="button secondary" onClick={() => setPreview(undefined)}>Back</button><button className="button" disabled={loading || !preview.importableRows} onClick={() => post("/api/imports/trips")}>{loading ? <LoaderCircle className="spin" /> : null} Import {preview.importableRows} trips</button></div></section>}
    {result && <section className="import-success"><span><Check /></span><h2>Trips are in the logbook.</h2><p>{result}</p><a className="button" href="/trips">See all trips</a></section>}{error && <div className="error-banner"><AlertTriangle /> <span><strong>We couldn’t process that file.</strong>{error}</span></div>}
  </div>;
}
